### ISSUE TITLE
Allow building an ISO image for the provisioning host

### ISSUE THREAD

**Issue by markmc** [openshift-kni/install-scripts#20]
We should provide a pre-configured operating system (as an ISO image on an SD card) for the provisioning host to ease the installation process. The goal is to speed up the installation and to avoid having to handle any OS or component compatibility concerns.

In short, the ISO image should contain the results of running the [install_requirements](https://github.com/openshift-kni/install-scripts/blob/master/01_install_requirements.sh) and [configure_host](https://github.com/openshift-kni/install-scripts/blob/master/02_configure_host.sh) scripts.

**Comment by russellb** [comment]
If we are talking about a pretty small number of clusters, is the work or building a custom ISO saving enough to make it worth the effort? How much easier will the install be with this ISO vs just running the scripts that do the same setup in a short amount of time?

**Comment by rlopez133** [comment]
Hey Russell and Mark,

Regarding the  "the work or building a custom ISO saving enough to make it worth the effort?" The work at this point should be minimal because our team (Integration team) has created the custom slim ISO already. In fact, we are working out the details to have this CI'ed in our environment. As far as time saver goes, when I did a comparison test between using dev-scripts as is vs using the custom slim ISO, it shaved install time by 25%. 

Regarding "How much easier will install be with ISO vs just running scripts", the reason we came up with the creation of the custom ISO was because of the following criteria:

* iDRAC access is on an isolated network
* The physical hardware has no DVD ROM drive
* No PXE access on the environment

This left us with we need to have an ISO to install an OS on the provisioner node. The 2 options that we came up with were A) use the vFlash SD card for the ISO image B) use a thumb drive for the ISO image. We chose option A. 

Another reason for the custom ISO is updating the provisioner node OS. Based on discussions within the program meeting, it was determined to avoid having customers use subscription-manager. Right now the 01_install_requirements.sh updates using yum update. However, without enabling sub manager this won't be an option. To solve this, we went ahead and captured the latest CDN packages required and then updated those packages on the custom ISO itself thus removing the issue of updating your provisioner node without a registered system. 

Anyway, I wanted to share this as to the why the custom ISO came about in the first place.

**Comment by markmc** [comment]
ok, in summary:

- Goal: Pre-install the provisioning node with dependencies and any configuration that is not environment specific
- Why: reduce overall on-site install time and avoid the sometimes awkward step of entitling the provisioning node with the appropriate subscription
- Constraints: the pre-install will happen on an isolated network with no PXE or DVD drive

**Comment by rlopez133** [comment]
Being done but not part of install-scripts.

**Comment by eldar101** [comment]
Does this ISO file exist?

> Being done but not part of install-scripts.
