### ISSUE TITLE
Create ConfigMap needed to configure baremetal-operator

### ISSUE THREAD

**Issue by russellb** [openshift-kni/install-scripts#30]
The baremetal-operator is now automatically launched by the machine-api-operator.  However, the baremetal-operator requires a ConfigMap for some configuration details and this is not yet automatically created.  Instead, we must create it here and add it to the manifests that should be applied by the installer.  This can't be done post-install, as it's needed for cluster installation to complete successfully.  Otherwise, the machine-api-operator will report a failure.

Here is the template used by openshift-metal3/dev-scripts:

https://github.com/openshift-metal3/dev-scripts/blob/master/metal3-config.yaml

**Comment by russellb** [comment]
Note that we must also create a `Secret` called `mariadb-password` to configure the metal3 deployment

**Comment by markmc** [comment]
I had greatly hoped we would avoid using custom manifests via `create manifests` - is there no hope of having this manifest generated by the installer in 4.2? Got a link to the related OpenShift issue?

**Comment by dhellmann** [comment]
The installer cannot create a ConfigMap because it wouldn’t be versioned and so upgrades would be harder/impossible. The installer can, and does, add settings to the infrastructure config CR, but that does not yet have enough of the information we need for metal3. We therefore either need to define a new CRD for configuring metal3, or extend the existing CRD to hold the new values. The metal3 deployment cannot read settings out of a CR directly, so we need an operator (probably the machine-api-operator) to read them and pass them (either directly, or via a ConfigMap).

I would not expect to be able to do all of that work for 4.2.

**Comment by russellb** [comment]
I think this is worth revisiting to save us a step.  I'd argue that it should be acceptable in 4.2 under the following conditions: the `baremetal` platform is still experimental, we will not support upgrades from 4.2 to 4.3 of these clusters, and we'll commit to removing the ConfigMap before coming out of experimental

cc @imain since you had a PR up to the installer for this - want to restore it and we can continue discussing there?

In the meantime though, we'll see need to do this in our scripts ...

**Comment by markmc** [comment]
For reference - https://github.com/openshift/installer/pull/2149#issuecomment-517935104 is where we discussed this

Along the lines of Russell's list of conditions - why is it not ok for the installer in 4.2 to create an unversioned object but it is ok to require the user to create one?

If we stick with the current approach the docs will need to look something like this:

https://github.com/markmc/installer/blob/bmo-config/docs/user/metal/install_ipi.md#installation-process
https://github.com/markmc/installer/blob/bmo-config/docs/user/metal/install_ipi.md#metal3-config

**Comment by dhellmann** [comment]
The installer PR is https://github.com/openshift/installer/pull/2149

**Comment by sreichar** [comment]
fixed by #89
