### ISSUE TITLE
config_user.sh and install-config.yaml both requried?

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#49]
Currently 02_configure_host.sh complains if no config_user.sh is found but I believe it was only necessary to have a valid install_config.yaml
Can someone confirm?

**Comment by sreichar** [comment]
My understanding - for the appliance case the need for config_user.sh will go away.

Current thinking is to attempt  to keep some of the scripts that allow more flexibity (non-appliance) so that someone could call them but they would not be part of the default flow.

Been waiting for preflight integration before making those changes.


But if you install using the latest ISO, there should be no reason to run either the 01 or 02 scripts.

**Comment by rlopez133** [comment]
Fixed by #92
